# Generated by Django 3.2.25 on 2024-10-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_mensagem_room_topico_delete_roommodel_mensagem_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-criada']},
        ),
        migrations.AlterField(
            model_name='room',
            name='criada',
            field=models.DateField(auto_now=True),
        ),
    ]
