# Generated by Django 3.2.25 on 2024-10-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_mensagem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='enviada',
            field=models.DateField(auto_now=True),
        ),
    ]
