# Generated by Django 3.2.25 on 2024-10-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_mensagem_enviada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
