# Generated by Django 3.2.25 on 2024-10-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20241016_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['-enviada']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-criada']},
        ),
    ]
