# Generated by Django 3.2.25 on 2024-10-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20241016_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='enviada',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='criada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
